
GhostKiller: main.c Assets.c TextManager.c Scene.c Player.c Shader.c ObjectsManager.c ViewFinder.c WaveManager.c Box.c Enemy.c Bullet.c
	gcc -o GhostKiller main.c Assets.c TextManager.c Scene.c Player.c Shader.c ObjectsManager.c ViewFinder.c WaveManager.c Box.c Enemy.c Bullet.c -lm -lSOIL -lGL -lGLEW -lglfw

clean:
	rm -f GhostKiller
